### ISSUE TITLE
Getting browser.on is not a function

### ISSUE THREAD

**Issue by maljukan** [ryscheng/karma-cordova-launcher#7]
Using karma 1.1.0 i can't run unit tests with exact configuration as in `readme.md`

This is the error i get when i run `karma start`:

`10 07 2016 04:07:12.139:INFO [launcher]: Starting browser undefined on Cordova
10 07 2016 04:07:12.140:ERROR [karma]: [TypeError: browser.on is not a function]
TypeError: browser.on is not a function
    at Object.j (D:\lab\app\node_modules\karma\lib\launcher.js:96:17)
    at Object.setTimeout.bind.j (D:\lab\app\node_modules\qjobs\qjobs.js:143:18)
    at Timer.listOnTimeout (timers.js:92:15)
!!!EXITING!!!`

**Comment by janus-toendering** [comment]
Fixed by #10
